name: Elixir CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '24'
        elixir-version: '1.14.3'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
      env:
        MIX_ENV: test
    - name: Check compile warnings
      run: mix compile --warnings-as-errors
    - name: Check formatter
      run: mix format --check-formatted
    - name: Run credo
      run: mix credo --strict
    - name: Run tests
      run: mix coveralls.github
      env:
        MIX_ENV: test
        DB_PASSWORD: postgres
        DB_HOST: postgres
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
